#coding: utf-8
#title_en: Vercomicsporno
#https://vercomicsporno.com/
import downloader
from utils import Downloader, Session, clean_title


@Downloader.register
class Downloader_chochox(Downloader):
    type = 'vercomicsporno'
    URLS = ['vercomicsporno.com']
    icon = 'base64:AAABAAEAICAAAAEAIAAoEAAAFgAAACgAAAAgAAAAQAAAAAEAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAQAAAAAAAAAAAAAAAQAAMmaZBYGY3lmInOl0cYrTRoug6pOWqPHPmq7yv5Ss635zjMwUAQAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAgASis+6+tL///5ys//+VpvL/r7z//7vG///E0P//vc3//6a6+O+End08AAAAAAAAAAAAAAAAAAEAAAAAAAAAAAEAAAABAAAAAQAAAAAAAAEAAAAAAAABAAAAIyo7HjM5PlotMjZsHycuIQAAAAAAAAAAAAEAAAAAAAAAAAAAkqTdUsLL//+2wP//nq3y/7S//v+3wf//u8X//8XQ///N2f//uMr//6K4+O8ICvnLAAD/1wAA/t0AAP7cAAH+vgAA/i8AAQAAAAAAAAAAAAAAAQEAAAAAAAAAAAA8PUPgQkRG/0FDRf8yNDbzISUsRQAAAAAAAAAAAQAAAAAAAACote2Kvcf//7fC/f+erej/xc7//7vF///Ayv//x9P//8/a///F1P//r8P//0FL9P8AAf//AAH//wAA//8BAP//AAD9owAAAAAAAAAAAQAAAAAAAQAAAAAAAAAAADE4Pk4+QUT1QkRG/0JERv8vMTXpICo1GAAAAQAAAAAAAAAAALC/75fF0f//s8D2/46d4/7F0P//xdH//8jT/v/N2P//0d3//8vY//+qv/v/g7zu/03W6v9M0uv/LXny/wIC/f8AAP7sAQD/AgEBAAAAAAAAAQAAAAAAAAAAAAAAAAAAAC40PTZAQkX2QkRG/z5AQv8pLDHzJCgtgQEAAAEAAAAAtcTqhs3Z///D0P3/ipvd/sTR+P/O2f//z9v//9Hd///S3v//y9n//6i89P+Sv/H/UN7q/1He6v+Dxev/kaH1/xAU+f8FCv81AQAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAADc7QYpDRUb/QkVG/z5AQv8pKy3/JCcvVgABAACvv+Zo0t3//8bV//+gte//l6C4/4iRpP+Qma7/rrnV/9Lf///F1P//tcf0/5+89f9Q2+j/Ud7q/6XI8P/T3/7/nq72/wwV93sAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAICAwED1BROtCREb/QkRG/y4vMv8lKjFoAAAAAIuizDegqsP/e4Wh/258of9CREb/QkRG/0JFRv9CREb/ZGp1/6q87P++zvX/r8P+/2bJ5v9Q2Of/vs/4/8LR9f/T3///gZLyvwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAANTg/aUJER/9DREb/Ky0x/xspNyYBAAAAIS40J0JERv83ODv/Jigs/z9BRP9CREb/QkRG/0NERv89PkH/SlNo/7HD9P+ht/T/lrbv/1zE4P/J1v//ytj5/8TS9f/I1/r6fZrVKwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFUDPT9CykJERv86PT7/JScttQAAQAQUHTEaQkRG/z5AQv8oKSz/Oj1B/0JERv9CREb/QkRG/zU2Of9PU2D/ztv//8bT//+vwPr/i6nl/5am1P+0wOX/bnnw/6Sw9v+rwe+6AAAAAAEAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAAuNDosQUNF90JERv82Nzr/JSgtrhAgMRA9QUT7QkRG/yssL/84Oj7/Q0RG/0JERv9CREb/LzAz/32Dl/+6yfX/prXw/7/J//+Ln9z/UGWP/8LO8f+Fkdz/MjrU/8vZ/P+swO2RgKLcFgAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAA0Nz5mQkRH/0JERv84Ojz/Jyos3TA0OfdBQ0X/MDI0/zQ3O/9CREb/QkRH/0JERv8pKi3/r7jV/6++8/+Yqev/ucT+/2+Atf9of6P/kaLF/5us0v9AU4r/xNL1/8TS9f+pvOvmcpLLMQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2OUGOQkRG/0JERv8/QEP/MTI1/ykrL/8qLDH/MTM3/0JERv9CREb/PT9B/zc6R/+wwfH/zNj//8XP/v/Czf//U2eW/3mPr/+Cl7f/domx/0JZg/+MoMn/k6fQaKa54mqOqNy5bYnGNgAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAEAAAI6PUGoQkRG/0JERv9CREb/Oj0+/ykrLv8tMDb/QkRG/0JERv83OTv/cXiO/8HO/P+8zPb/ws/4/6/A9v9LYI7/eo+x/4KXt/90iKz/QliD/3+Vv/8xSYdiAAAAAICZzBR2lM9fAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAACQkJAc6PEK6QkRG/0JFRv9CREb/PkBC/ywuMv9CREb/QkRG/zAxNP+QnsD/v8z0/8HP9f+mt93/u83//11yo/9vhKf/gpe3/3SIq/9KX4n/QlmD/yQyrKgAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAABcuLgs8P0PFQ0RG/0JERv9CRUb/Oz1A/z9AQv9CREb/Lz5J/32Ss/9ofab/dIq3/5Wo2v+ovfT/eIzD/1pxl/+Blrb/ZHif/0pfif9CWYL/DhLX6QAA/wMAAAAAAQABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAADI3Pms9QET/QkRG/0JFR/9CREb/PkFD/zw+Qf81aH3/a4Cl/01kjf99hrr/iIS//7nC7f+xwvT/TmOS/05kjf9ofaL/QVeC/zdKjf8AAPz/AAD/LgAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAABAAAAAAAAAQAAAAAAAAAyOD5XP0JE/UBCRP89QET/QkRG/0JERv9CREf/Nz9D/03S3v9dnLz/bYKq/7S/7P+3w/H/xc/8/8TP//+Nn9z/V2uU/1Nokf9EW4X/KDLF/wAB/v8AAP9qAAAAAAAAAAAAAAAAAAAAAAAAAQABAAAAAAAAAAABAAAAAAAAKDA4ID9CRfNCREb/QkRG/zEzNv85Uln/QkRG/0JERv8/fIT/UN7q/zVo3f+KnMX/vMj5/8TR/f++x/H/oYyo/4CSyP96jrD/QliD/2yCp/8eQur/AAD//wEA/aQBAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAA5PkKhQkRG/0JERv87PT//MFdf/0/d6f9GqrX/Q4KK/0zN2f9O1+v/CRDy/3CCpvyYe4X7wc/2/8XP6/+Jc4H/Y3GN/26Dp/9Zb5b/bpm5/zKK8v8AAP//AAD+3QAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJCQxFT9BRflCREf/QUNF/y01Of9JxNH/UN/q/1Df6v9Q3+r/UN7q/zqg8P8DBPP/Ynme/oybw//T3///tL/a/15slf9sfpr/Yned/3aMrv9mpsL/RLzs/wAB//8AAP7+AAD/GAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAA0OUBnQkRG/0JER/82ODv/OIKY/1He6v9Q3ur/UN7q/1De6v9Q3ur/I2H2/yAl4f9jeJ3/usXj/9Pf///T3///coSt/4CUtP9bcZf/g5e3/2GvyP9Q3er/BxH+/wAB//8AAP9NAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAEAADo+QsBCREb/P0BD/x4hYf9Gwev/UN/q/1He6v9Q3+r/UN/q/1De6v8MIPz/N0DC/3mNr/96j73/mKfP/5+u1v92jK7/bIGl/3eMrv+Cl7f/WrfO/1De6v8XP/n/AAD//wAA/YEAAAAAAAAAAAAAAAAAAAAAAAAzBQAAAAAqMjgkQUJF/kJERv8rLTv/FjXc/1De6v9Q3ur/UN7q/1De6v9Q3ur/RL7t/wEB+/8ZHbq2T2GN1Gh9ov9meaH/a36l/3iMr/+So7//pLPK/4CYuf9P0OH/UN7q/ydt9f8AAP//AAD/swAAAAAAAAAAAAAAACAgMBA9QULqOjxC0zY5PrBCREb/MjM3/w4QpvktfPT/UN7q/1De6v9Q3ur/UN7q/1De6v8tffP/AAD//wAA/ysAAAAAVGOSNl5tt6lmfbj/YXqg/2mMsP9wob7/ZMrc/1De6/9R3ur/N5nw/wEA//8AAP7fAAAAAAAAAAAAAAAAMDQ/RUJFRv9CREb/PT9A/zAxNf8cIEKtAQP990jG7P9Q3ur/Ud7q/1De6v9Q3ur/UN7q/xU7+v8AAP7ZAAD+AQAAAAAAAAAAAAH/LR1Q+P9Q3ur/UN7q/1De6v9Q3ur/UN/q/1He6v9Gwu3/AAD//wAA/vsAAP8JAAAAAAAAVQM7PkO9QkRG/0BCRP8qKy7/JCgumgAA+nEXQfn/UN7r/1De6v9Q3ur/UN7q/1De6v9Lz+z/AgX//wEA/YYAAAAAAAAAAAAAAAAAAP4ECRz78FDe6v9Q3ur/UN7q/1De6/9Q3ur/UN7q/0/c6v8DCP7/AAH+/gAA/xQAAAAANDlAZ0JERv9CREb/MzU4/iQoLoAAAP8BAAD+0hlF+P0ugPP/NJDy/zqg8P8/sO7/RsDt/y+C8/8AAP7tAAD/IwAAAAAAAAAAAAAAAAAAAAAAAf67R8bs/1De6v9Q3ur/UN7q/1De6v9Q3ur/UN/q/wob/f8BAP7jAAD+AQAAAAA4PkGgQkRG/zc5PP4hJy5jAAAAAAAAAAAAAP8JAAD/HwAA/zkAAP9RAAD/agEA/YMAAP2cAAD+tAAA/zMAAAAAAQAAAAAAAAAAAAAAAAAAAAEA/YQ2l/H/UN7q/1De6v9Q3ur/UN7q/0vQ6v8+re//AwX++gAB/1gAAAAAAAAAADo+Q5lCREb/LjE2pgAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAD/PAIN/dMPKvr2FDb6/w8s+vcIFPzdAQH+uwAA/ZUAAP9MAAAAAAAAAAAAAAAANztCcEJERv8yNjuOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAEAAAAAAQAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXLi4LOjxCljE1O34AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAA'
    display_name = 'Vercomicsporno'
    MAX_CORE = 4
    ACCEPT_COOKIES = [r'(.*\.)?(vercomicsporno\.com)']

    def read(self):
        self.session = Session()
        self.referer = self.url
        info = get_imgs_www(self.url, self.referer, self.session)
        for img in info['imgs']:
            self.urls.append(img)
        self.title = clean_title(info['title'])

def get_imgs_www(url,referer,session):
    #soup = Soup(downloader.read_html(url, session=session))
    soup = downloader.read_soup(url, referer=referer, session=session)
    info = {}
    imgs = []
    info['title'] = soup.find('h1').text.strip()
    view = soup.find('div', class_='wp-content').findAll('noscript')
    for imgv in view:
        img = imgv.find('img').attrs['src']
        if not img or not img.startswith('http'):
            continue
        imgs.append(img)
    if '/girlD.png' in imgs[-1] or '/descargavcp.png' in imgs[-1] :
        imgs.pop()
    info['imgs'] = imgs
    return info